server:
  port: 9090

eureka:
  instance:
    hostname: localhost
    appname: EurekaService
    prefer-ip-address: true
  client:
    # 表示是否将自己注册到Eureka Server，默认为true
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true
    fetch-registry: false
    service-url:
      # service启动的服务地址，即服务注册中心地址,map结构，defaultZone为 key值
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #关闭eureka的自我保护模式
  server:
    enable-self-preservation: false
spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/puer?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&serverTimezone=GMT%2B8&
#    username: root
#    password: root
  freemarker:
    #需要加下面这个配置，才能访问到 eureka 界面（对于 service 来说）
    prefer-file-system-access: false
  devtools:
    livereload:
      port: 35729
  application:
    name: service-hi
