spring:
  profiles:
    active: learn

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
#      url: jdbc:mysql://127.0.0.1:3306/newDev?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8
      url: jdbc:oracle:thin:@127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8
      username: root
      password: root
      first:  #数据源1
        url: jdbc:mysql://127.0.0.1:3306/newDev?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8
        username: root
        password: root
      second:  #数据源2
        url: jdbc:mysql://40.73.34.141:3306/dev?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true&characterEncoding=UTF-8
        username: root
        password: root
      #初始化
      initial-size: 10
      #最大
      max-active: 100
      #最小
      min-idle: 10
      #最大等待连接时间
      max-wait: 60000
      #打开PSCache,并且指定每个连接PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置间隔多久才进行一次检测,检测需要关闭的空闲连接,单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间,单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #配置监控统计拦截的filters,去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j
      filter:
        stat:
          #缺省值为3秒 此处修改为10秒
          slow-sql-millis: 10000
          #日志记录
          log-slow-sql: true

      #是否合并多个dataSource的监控数据
      use-global-data-source-stat: true

      #连接进行保活处理
      keep-alive: true
      #关闭长时间不用的连接
      remove-abandoned: true
      #长时间不用的连接的超时时间 单位秒
      remove-abandoned-timeout-millis: 1800
      #输出日志
      log-abandoned: true